# Travis CI (MIT License) configuration file for the Underscores WordPress theme
# @link https://travis-ci.org/
# For use with the Underscores WordPress theme
# @link https://github.com/Automattic/_s
# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
- "5.5"
env:
- WP_VERSION=4.1
before_script:
# remember root
- export travisroot_dir=$(pwd)
- export WP_DEVELOP_DIR=tmp/wordpress/
- mkdir -p $WP_DEVELOP_DIR
- git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
- plugin_slug=1000grad-epaper
- plugin_dir=$WP_DEVELOP_DIR'src/wp-content/plugins/'
- scp -r src/$plugin_slug $plugin_dir
# Set up WordPress configuration.
- cd $WP_DEVELOP_DIR
- echo $WP_DEVELOP_DIR
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
- sed -i "s/yourusernamehere/root/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
# Create WordPress database.
- mysql -e 'CREATE DATABASE wordpress_test;' -uroot
- cd $plugin_dir
- php -S 127.0.0.1:4000 &
- sleep 3
script:
- find . \( -name '*.php' \) -exec php -lf {} \;
- cd $travisroot_dir
notifications:
email: false